server.port=${PORT:8090}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
# Recommended for production or connection pooling stability
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

