spring.datasource.url=jdbc:postgresql://ep-snowy-bar-b4g4kooy-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Mw1abqSs2yYC
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8090
# Recommended for production or connection pooling stability
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10